In [15]:
import numpy as np
from numpy import genfromtxt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [4]:
data=genfromtxt('computer vision project/DATA/bank_note_data.txt',delimiter=',')

In [6]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [8]:
labels=data[:,4]

labels

In [10]:
features=data[:,0:4]

In [11]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [12]:
X=features
y=labels

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [16]:
scaler_obj=MinMaxScaler()

In [17]:
scaler_obj.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [18]:
scaled_X_train=scaler_obj.transform(X_train)

In [19]:
scaled_X_test=scaler_obj.transform(X_test)

In [20]:
scaled_X_train.max()

1.0000000000000002

In [21]:
scaled_X_train.min()

0.0

In [22]:
scaled_X_test.max()

1.02679563427227

In [23]:
scaled_X_test.min()

-0.0010694864308909147

In [25]:
from keras.models import Sequential
from keras.layers import Dense

In [29]:
model=Sequential()
model.add(Dense(4,input_dim=4,activation='relu'))#input layer
model.add(Dense(8,activation='relu'))#hidden layer
model.add(Dense(1,activation='sigmoid'))#output layer

In [30]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [31]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 0s - loss: 0.6988 - acc: 0.4135
Epoch 2/50
 - 0s - loss: 0.6918 - acc: 0.5495
Epoch 3/50
 - 0s - loss: 0.6875 - acc: 0.5495
Epoch 4/50
 - 0s - loss: 0.6829 - acc: 0.5495
Epoch 5/50
 - 0s - loss: 0.6765 - acc: 0.5495
Epoch 6/50
 - 0s - loss: 0.6633 - acc: 0.5495
Epoch 7/50
 - 0s - loss: 0.6526 - acc: 0.5495
Epoch 8/50
 - 0s - loss: 0.6417 - acc: 0.5495
Epoch 9/50
 - 0s - loss: 0.6295 - acc: 0.5669
Epoch 10/50
 - 0s - loss: 0.6166 - acc: 0.6333
Epoch 11/50
 - 0s - loss: 0.6033 - acc: 0.6866
Epoch 12/50
 - 0s - loss: 0.5889 - acc: 0.7008
Epoch 13/50
 - 0s - loss: 0.5728 - acc: 0.7378
Epoch 14/50
 - 0s - loss: 0.5559 - acc: 0.7476
Epoch 15/50
 - 0s - loss: 0.5373 - acc: 0.7748
Epoch 16/50
 - 0s - loss: 0.5181 - acc: 0.7933
Epoch 17/50
 - 0s - loss: 0.4956 - acc: 0.8118
Epoch 18/50
 - 0s - loss: 0.4715 - acc: 0.8292
Epoch 19/50
 - 0s - loss: 0.4476 - acc: 0.8651
Epoch 20/50
 - 0s - loss: 0.4234 - acc: 0.8607
Epoch 21/50
 - 0s - loss: 0.3995 - acc: 0.8868
Epoch 22/50
 - 0s - lo

In [34]:
model.metrics_names

['loss', 'acc']

In [35]:
from sklearn.metrics import confusion_matrix,classification_report

In [36]:
prediction=model.predict_classes(scaled_X_test)

In [37]:
confusion_matrix(y_test,prediction)

array([[251,   6],
       [ 10, 186]], dtype=int64)

In [38]:
print(classification_report(y_test,prediction))

             precision    recall  f1-score   support

        0.0       0.96      0.98      0.97       257
        1.0       0.97      0.95      0.96       196

avg / total       0.96      0.96      0.96       453



In [39]:
model.save('model1.h5')

In [40]:
from keras.models import load_model

In [41]:
new_model=load_model('model1.h5')

In [43]:
new_model.predict_classes(scaled_X_test)

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    